/home/nisoni/eihart/EIHaRT/examples/finetuning/hart/stance_LR_5e5best_aftertrials_wodecay/abo.sh /chronos_data/nisoni/eihart_outputs/PT/5e5_eihart_100pc_8ep_hsc_ce_mse_hart_age/checkpoint-113860
/home/nisoni/eihart/EIHaRT/examples/finetuning/hart/stance_LR_5e5best_aftertrials_wodecay/ath.sh /chronos_data/nisoni/eihart_outputs/PT/5e5_eihart_100pc_8ep_hsc_ce_mse_hart_age/checkpoint-113860
/home/nisoni/eihart/EIHaRT/examples/finetuning/hart/stance_LR_5e5best_aftertrials_wodecay/clim.sh /chronos_data/nisoni/eihart_outputs/PT/5e5_eihart_100pc_8ep_hsc_ce_mse_hart_age/checkpoint-113860
/home/nisoni/eihart/EIHaRT/examples/finetuning/hart/stance_LR_5e5best_aftertrials_wodecay/clin.sh /chronos_data/nisoni/eihart_outputs/PT/5e5_eihart_100pc_8ep_hsc_ce_mse_hart_age/checkpoint-113860
/home/nisoni/eihart/EIHaRT/examples/finetuning/hart/stance_LR_5e5best_aftertrials_wodecay/fem.sh /chronos_data/nisoni/eihart_outputs/PT/5e5_eihart_100pc_8ep_hsc_ce_mse_hart_age/checkpoint-113860
